/*
Product Configurator Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProductconfiguratorpropertyBulkCreateRequestCreateEntity struct for ProductconfiguratorpropertyBulkCreateRequestCreateEntity
type ProductconfiguratorpropertyBulkCreateRequestCreateEntity struct {
	StepIdToOptionId *map[string]string `json:"stepIdToOptionId,omitempty"`
	GenericProperty *ProductconfiguratorpropertyGenericProperty `json:"genericProperty,omitempty"`
	PriceProperty *ProductconfiguratorpropertyPriceProperty `json:"priceProperty,omitempty"`
	WeightProperty *ProductconfiguratorpropertyWeightProperty `json:"weightProperty,omitempty"`
}

// NewProductconfiguratorpropertyBulkCreateRequestCreateEntity instantiates a new ProductconfiguratorpropertyBulkCreateRequestCreateEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductconfiguratorpropertyBulkCreateRequestCreateEntity() *ProductconfiguratorpropertyBulkCreateRequestCreateEntity {
	this := ProductconfiguratorpropertyBulkCreateRequestCreateEntity{}
	return &this
}

// NewProductconfiguratorpropertyBulkCreateRequestCreateEntityWithDefaults instantiates a new ProductconfiguratorpropertyBulkCreateRequestCreateEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductconfiguratorpropertyBulkCreateRequestCreateEntityWithDefaults() *ProductconfiguratorpropertyBulkCreateRequestCreateEntity {
	this := ProductconfiguratorpropertyBulkCreateRequestCreateEntity{}
	return &this
}

// GetStepIdToOptionId returns the StepIdToOptionId field value if set, zero value otherwise.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetStepIdToOptionId() map[string]string {
	if o == nil || isNil(o.StepIdToOptionId) {
		var ret map[string]string
		return ret
	}
	return *o.StepIdToOptionId
}

// GetStepIdToOptionIdOk returns a tuple with the StepIdToOptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetStepIdToOptionIdOk() (*map[string]string, bool) {
	if o == nil || isNil(o.StepIdToOptionId) {
    return nil, false
	}
	return o.StepIdToOptionId, true
}

// HasStepIdToOptionId returns a boolean if a field has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) HasStepIdToOptionId() bool {
	if o != nil && !isNil(o.StepIdToOptionId) {
		return true
	}

	return false
}

// SetStepIdToOptionId gets a reference to the given map[string]string and assigns it to the StepIdToOptionId field.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) SetStepIdToOptionId(v map[string]string) {
	o.StepIdToOptionId = &v
}

// GetGenericProperty returns the GenericProperty field value if set, zero value otherwise.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetGenericProperty() ProductconfiguratorpropertyGenericProperty {
	if o == nil || isNil(o.GenericProperty) {
		var ret ProductconfiguratorpropertyGenericProperty
		return ret
	}
	return *o.GenericProperty
}

// GetGenericPropertyOk returns a tuple with the GenericProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetGenericPropertyOk() (*ProductconfiguratorpropertyGenericProperty, bool) {
	if o == nil || isNil(o.GenericProperty) {
    return nil, false
	}
	return o.GenericProperty, true
}

// HasGenericProperty returns a boolean if a field has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) HasGenericProperty() bool {
	if o != nil && !isNil(o.GenericProperty) {
		return true
	}

	return false
}

// SetGenericProperty gets a reference to the given ProductconfiguratorpropertyGenericProperty and assigns it to the GenericProperty field.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) SetGenericProperty(v ProductconfiguratorpropertyGenericProperty) {
	o.GenericProperty = &v
}

// GetPriceProperty returns the PriceProperty field value if set, zero value otherwise.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetPriceProperty() ProductconfiguratorpropertyPriceProperty {
	if o == nil || isNil(o.PriceProperty) {
		var ret ProductconfiguratorpropertyPriceProperty
		return ret
	}
	return *o.PriceProperty
}

// GetPricePropertyOk returns a tuple with the PriceProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetPricePropertyOk() (*ProductconfiguratorpropertyPriceProperty, bool) {
	if o == nil || isNil(o.PriceProperty) {
    return nil, false
	}
	return o.PriceProperty, true
}

// HasPriceProperty returns a boolean if a field has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) HasPriceProperty() bool {
	if o != nil && !isNil(o.PriceProperty) {
		return true
	}

	return false
}

// SetPriceProperty gets a reference to the given ProductconfiguratorpropertyPriceProperty and assigns it to the PriceProperty field.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) SetPriceProperty(v ProductconfiguratorpropertyPriceProperty) {
	o.PriceProperty = &v
}

// GetWeightProperty returns the WeightProperty field value if set, zero value otherwise.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetWeightProperty() ProductconfiguratorpropertyWeightProperty {
	if o == nil || isNil(o.WeightProperty) {
		var ret ProductconfiguratorpropertyWeightProperty
		return ret
	}
	return *o.WeightProperty
}

// GetWeightPropertyOk returns a tuple with the WeightProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) GetWeightPropertyOk() (*ProductconfiguratorpropertyWeightProperty, bool) {
	if o == nil || isNil(o.WeightProperty) {
    return nil, false
	}
	return o.WeightProperty, true
}

// HasWeightProperty returns a boolean if a field has been set.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) HasWeightProperty() bool {
	if o != nil && !isNil(o.WeightProperty) {
		return true
	}

	return false
}

// SetWeightProperty gets a reference to the given ProductconfiguratorpropertyWeightProperty and assigns it to the WeightProperty field.
func (o *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) SetWeightProperty(v ProductconfiguratorpropertyWeightProperty) {
	o.WeightProperty = &v
}

func (o ProductconfiguratorpropertyBulkCreateRequestCreateEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.StepIdToOptionId) {
		toSerialize["stepIdToOptionId"] = o.StepIdToOptionId
	}
	if !isNil(o.GenericProperty) {
		toSerialize["genericProperty"] = o.GenericProperty
	}
	if !isNil(o.PriceProperty) {
		toSerialize["priceProperty"] = o.PriceProperty
	}
	if !isNil(o.WeightProperty) {
		toSerialize["weightProperty"] = o.WeightProperty
	}
	return json.Marshal(toSerialize)
}

type NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity struct {
	value *ProductconfiguratorpropertyBulkCreateRequestCreateEntity
	isSet bool
}

func (v NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity) Get() *ProductconfiguratorpropertyBulkCreateRequestCreateEntity {
	return v.value
}

func (v *NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity) Set(val *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductconfiguratorpropertyBulkCreateRequestCreateEntity(val *ProductconfiguratorpropertyBulkCreateRequestCreateEntity) *NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity {
	return &NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity{value: val, isSet: true}
}

func (v NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductconfiguratorpropertyBulkCreateRequestCreateEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


