/*
Product Configurator Service

 The Product Configurator Service is a versatile platform designed to manage dynamic product configurations.  It enables the creation, updating, and management of product configurations through steps, options, and dependencies,  ensuring granular control over customization.  ## Core Components 1. **Configurators**    - Create and manage configurators linked to products.    - Support for configurator states (`ACTIVE`, `DRAFT`, etc.) and versioning.  2. **Steps**    - Define logical sequences to guide users through the configuration process.    - Include localized labels, descriptions, and selection rules.  3. **Options**    - Add and manage options available for each step.    - Support for visual content (`Swatch`) and configurable quantities.  4. **Dependencies**    - Create rules between options and steps to control dynamic interactions.    - Manage complex conditions across configurations.  5. **Matrices**    - Use matrices to handle prices, weights, and other properties.    - Support for dynamic customization based on user selections.  6. **Properties**    - Add custom attributes and properties to configurators.  7. **Configuration Management**    - Retrieve available or user-specific configurations.    - Create optimized configurations to enhance the user experience.  ## Key Features - **Security**: Authenticate every request with JWT, ensuring safety and reliability. - **Flexibility**: Bulk operations (create, update, delete) for steps, options, and dependencies. - **Scalability**: Suitable for large volumes of configurations and complex personalization scenarios. - **Backward Compatibility**: Version management to minimize the impact of changes on existing clients.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productconfigurator

import (
	"encoding/json"
)

// checks if the ConfigurationGetConfigurationFromSelectionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationGetConfigurationFromSelectionsResponse{}

// ConfigurationGetConfigurationFromSelectionsResponse struct for ConfigurationGetConfigurationFromSelectionsResponse
type ConfigurationGetConfigurationFromSelectionsResponse struct {
	Steps                []ConfigurationConfigurationStep `json:"steps,omitempty"`
	MatchedProperties    []ConfigurationProperty          `json:"matchedProperties,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConfigurationGetConfigurationFromSelectionsResponse ConfigurationGetConfigurationFromSelectionsResponse

// NewConfigurationGetConfigurationFromSelectionsResponse instantiates a new ConfigurationGetConfigurationFromSelectionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationGetConfigurationFromSelectionsResponse() *ConfigurationGetConfigurationFromSelectionsResponse {
	this := ConfigurationGetConfigurationFromSelectionsResponse{}
	return &this
}

// NewConfigurationGetConfigurationFromSelectionsResponseWithDefaults instantiates a new ConfigurationGetConfigurationFromSelectionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationGetConfigurationFromSelectionsResponseWithDefaults() *ConfigurationGetConfigurationFromSelectionsResponse {
	this := ConfigurationGetConfigurationFromSelectionsResponse{}
	return &this
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) GetSteps() []ConfigurationConfigurationStep {
	if o == nil || IsNil(o.Steps) {
		var ret []ConfigurationConfigurationStep
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) GetStepsOk() ([]ConfigurationConfigurationStep, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) IsSetSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []ConfigurationConfigurationStep and assigns it to the Steps field.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) SetSteps(v []ConfigurationConfigurationStep) {
	o.Steps = v
}

// GetMatchedProperties returns the MatchedProperties field value if set, zero value otherwise.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) GetMatchedProperties() []ConfigurationProperty {
	if o == nil || IsNil(o.MatchedProperties) {
		var ret []ConfigurationProperty
		return ret
	}
	return o.MatchedProperties
}

// GetMatchedPropertiesOk returns a tuple with the MatchedProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) GetMatchedPropertiesOk() ([]ConfigurationProperty, bool) {
	if o == nil || IsNil(o.MatchedProperties) {
		return nil, false
	}
	return o.MatchedProperties, true
}

// HasMatchedProperties returns a boolean if a field has been set.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) IsSetMatchedProperties() bool {
	if o != nil && !IsNil(o.MatchedProperties) {
		return true
	}

	return false
}

// SetMatchedProperties gets a reference to the given []ConfigurationProperty and assigns it to the MatchedProperties field.
func (o *ConfigurationGetConfigurationFromSelectionsResponse) SetMatchedProperties(v []ConfigurationProperty) {
	o.MatchedProperties = v
}

func (o ConfigurationGetConfigurationFromSelectionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationGetConfigurationFromSelectionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	if !IsNil(o.MatchedProperties) {
		toSerialize["matchedProperties"] = o.MatchedProperties
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigurationGetConfigurationFromSelectionsResponse) UnmarshalJSON(data []byte) (err error) {
	varConfigurationGetConfigurationFromSelectionsResponse := _ConfigurationGetConfigurationFromSelectionsResponse{}

	err = json.Unmarshal(data, &varConfigurationGetConfigurationFromSelectionsResponse)

	if err != nil {
		return err
	}

	*o = ConfigurationGetConfigurationFromSelectionsResponse(varConfigurationGetConfigurationFromSelectionsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "steps")
		delete(additionalProperties, "matchedProperties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ConfigurationGetConfigurationFromSelectionsResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ConfigurationGetConfigurationFromSelectionsResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableConfigurationGetConfigurationFromSelectionsResponse struct {
	value *ConfigurationGetConfigurationFromSelectionsResponse
	isSet bool
}

func (v NullableConfigurationGetConfigurationFromSelectionsResponse) Get() *ConfigurationGetConfigurationFromSelectionsResponse {
	return v.value
}

func (v *NullableConfigurationGetConfigurationFromSelectionsResponse) Set(val *ConfigurationGetConfigurationFromSelectionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationGetConfigurationFromSelectionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationGetConfigurationFromSelectionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationGetConfigurationFromSelectionsResponse(val *ConfigurationGetConfigurationFromSelectionsResponse) *NullableConfigurationGetConfigurationFromSelectionsResponse {
	return &NullableConfigurationGetConfigurationFromSelectionsResponse{value: val, isSet: true}
}

func (v NullableConfigurationGetConfigurationFromSelectionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationGetConfigurationFromSelectionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
