/*
Product Configurator Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ProductconfiguratorstepBulkCreateResponse struct for ProductconfiguratorstepBulkCreateResponse
type ProductconfiguratorstepBulkCreateResponse struct {
	Steps []ProductconfiguratorstepEntity `json:"steps,omitempty"`
}

// NewProductconfiguratorstepBulkCreateResponse instantiates a new ProductconfiguratorstepBulkCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductconfiguratorstepBulkCreateResponse() *ProductconfiguratorstepBulkCreateResponse {
	this := ProductconfiguratorstepBulkCreateResponse{}
	return &this
}

// NewProductconfiguratorstepBulkCreateResponseWithDefaults instantiates a new ProductconfiguratorstepBulkCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductconfiguratorstepBulkCreateResponseWithDefaults() *ProductconfiguratorstepBulkCreateResponse {
	this := ProductconfiguratorstepBulkCreateResponse{}
	return &this
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *ProductconfiguratorstepBulkCreateResponse) GetSteps() []ProductconfiguratorstepEntity {
	if o == nil || isNil(o.Steps) {
		var ret []ProductconfiguratorstepEntity
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorstepBulkCreateResponse) GetStepsOk() ([]ProductconfiguratorstepEntity, bool) {
	if o == nil || isNil(o.Steps) {
    return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *ProductconfiguratorstepBulkCreateResponse) HasSteps() bool {
	if o != nil && !isNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []ProductconfiguratorstepEntity and assigns it to the Steps field.
func (o *ProductconfiguratorstepBulkCreateResponse) SetSteps(v []ProductconfiguratorstepEntity) {
	o.Steps = v
}

func (o ProductconfiguratorstepBulkCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	return json.Marshal(toSerialize)
}

type NullableProductconfiguratorstepBulkCreateResponse struct {
	value *ProductconfiguratorstepBulkCreateResponse
	isSet bool
}

func (v NullableProductconfiguratorstepBulkCreateResponse) Get() *ProductconfiguratorstepBulkCreateResponse {
	return v.value
}

func (v *NullableProductconfiguratorstepBulkCreateResponse) Set(val *ProductconfiguratorstepBulkCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductconfiguratorstepBulkCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductconfiguratorstepBulkCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductconfiguratorstepBulkCreateResponse(val *ProductconfiguratorstepBulkCreateResponse) *NullableProductconfiguratorstepBulkCreateResponse {
	return &NullableProductconfiguratorstepBulkCreateResponse{value: val, isSet: true}
}

func (v NullableProductconfiguratorstepBulkCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductconfiguratorstepBulkCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


