/*
Product Configurator Service

 The Product Configurator Service is a versatile platform designed to manage dynamic product configurations.  It enables the creation, updating, and management of product configurations through steps, options, and dependencies,  ensuring granular control over customization.  ## Core Components 1. **Configurators**    - Create and manage configurators linked to products.    - Support for configurator states (`ACTIVE`, `DRAFT`, etc.) and versioning.  2. **Steps**    - Define logical sequences to guide users through the configuration process.    - Include localized labels, descriptions, and selection rules.  3. **Options**    - Add and manage options available for each step.    - Support for visual content (`Swatch`) and configurable quantities.  4. **Dependencies**    - Create rules between options and steps to control dynamic interactions.    - Manage complex conditions across configurations.  5. **Matrices**    - Use matrices to handle prices, weights, and other properties.    - Support for dynamic customization based on user selections.  6. **Properties**    - Add custom attributes and properties to configurators.  7. **Configuration Management**    - Retrieve available or user-specific configurations.    - Create optimized configurations to enhance the user experience.  ## Key Features - **Security**: Authenticate every request with JWT, ensuring safety and reliability. - **Flexibility**: Bulk operations (create, update, delete) for steps, options, and dependencies. - **Scalability**: Suitable for large volumes of configurations and complex personalization scenarios. - **Backward Compatibility**: Version management to minimize the impact of changes on existing clients.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productconfigurator

import (
	"encoding/json"
)

// checks if the OptionSwatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OptionSwatch{}

// OptionSwatch Defines the visual representation of an option, including a GRN and URL for the associated content.
type OptionSwatch struct {
	// The global resource name for the swatch.
	Grn *string `json:"grn,omitempty"`
	// The URL pointing to the swatch content.
	Url                  *string `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OptionSwatch OptionSwatch

// NewOptionSwatch instantiates a new OptionSwatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOptionSwatch() *OptionSwatch {
	this := OptionSwatch{}
	return &this
}

// NewOptionSwatchWithDefaults instantiates a new OptionSwatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionSwatchWithDefaults() *OptionSwatch {
	this := OptionSwatch{}
	return &this
}

// GetGrn returns the Grn field value if set, zero value otherwise.
func (o *OptionSwatch) GetGrn() string {
	if o == nil || IsNil(o.Grn) {
		var ret string
		return ret
	}
	return *o.Grn
}

// GetGrnOk returns a tuple with the Grn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionSwatch) GetGrnOk() (*string, bool) {
	if o == nil || IsNil(o.Grn) {
		return nil, false
	}
	return o.Grn, true
}

// HasGrn returns a boolean if a field has been set.
func (o *OptionSwatch) IsSetGrn() bool {
	if o != nil && !IsNil(o.Grn) {
		return true
	}

	return false
}

// SetGrn gets a reference to the given string and assigns it to the Grn field.
func (o *OptionSwatch) SetGrn(v string) {
	o.Grn = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *OptionSwatch) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OptionSwatch) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *OptionSwatch) IsSetUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *OptionSwatch) SetUrl(v string) {
	o.Url = &v
}

func (o OptionSwatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OptionSwatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Grn) {
		toSerialize["grn"] = o.Grn
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OptionSwatch) UnmarshalJSON(data []byte) (err error) {
	varOptionSwatch := _OptionSwatch{}

	err = json.Unmarshal(data, &varOptionSwatch)

	if err != nil {
		return err
	}

	*o = OptionSwatch(varOptionSwatch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grn")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *OptionSwatch) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *OptionSwatch) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableOptionSwatch struct {
	value *OptionSwatch
	isSet bool
}

func (v NullableOptionSwatch) Get() *OptionSwatch {
	return v.value
}

func (v *NullableOptionSwatch) Set(val *OptionSwatch) {
	v.value = val
	v.isSet = true
}

func (v NullableOptionSwatch) IsSet() bool {
	return v.isSet
}

func (v *NullableOptionSwatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptionSwatch(val *OptionSwatch) *NullableOptionSwatch {
	return &NullableOptionSwatch{value: val, isSet: true}
}

func (v NullableOptionSwatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptionSwatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
