/*
Product Configurator Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DependencyListDependenciesResponse struct for DependencyListDependenciesResponse
type DependencyListDependenciesResponse struct {
	Dependencies []ProductconfiguratordependencyEntity `json:"dependencies,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewDependencyListDependenciesResponse instantiates a new DependencyListDependenciesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDependencyListDependenciesResponse() *DependencyListDependenciesResponse {
	this := DependencyListDependenciesResponse{}
	return &this
}

// NewDependencyListDependenciesResponseWithDefaults instantiates a new DependencyListDependenciesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDependencyListDependenciesResponseWithDefaults() *DependencyListDependenciesResponse {
	this := DependencyListDependenciesResponse{}
	return &this
}

// GetDependencies returns the Dependencies field value if set, zero value otherwise.
func (o *DependencyListDependenciesResponse) GetDependencies() []ProductconfiguratordependencyEntity {
	if o == nil || isNil(o.Dependencies) {
		var ret []ProductconfiguratordependencyEntity
		return ret
	}
	return o.Dependencies
}

// GetDependenciesOk returns a tuple with the Dependencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyListDependenciesResponse) GetDependenciesOk() ([]ProductconfiguratordependencyEntity, bool) {
	if o == nil || isNil(o.Dependencies) {
    return nil, false
	}
	return o.Dependencies, true
}

// HasDependencies returns a boolean if a field has been set.
func (o *DependencyListDependenciesResponse) HasDependencies() bool {
	if o != nil && !isNil(o.Dependencies) {
		return true
	}

	return false
}

// SetDependencies gets a reference to the given []ProductconfiguratordependencyEntity and assigns it to the Dependencies field.
func (o *DependencyListDependenciesResponse) SetDependencies(v []ProductconfiguratordependencyEntity) {
	o.Dependencies = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *DependencyListDependenciesResponse) GetNextPageToken() string {
	if o == nil || isNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyListDependenciesResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || isNil(o.NextPageToken) {
    return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *DependencyListDependenciesResponse) HasNextPageToken() bool {
	if o != nil && !isNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *DependencyListDependenciesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o DependencyListDependenciesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Dependencies) {
		toSerialize["dependencies"] = o.Dependencies
	}
	if !isNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}

type NullableDependencyListDependenciesResponse struct {
	value *DependencyListDependenciesResponse
	isSet bool
}

func (v NullableDependencyListDependenciesResponse) Get() *DependencyListDependenciesResponse {
	return v.value
}

func (v *NullableDependencyListDependenciesResponse) Set(val *DependencyListDependenciesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDependencyListDependenciesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDependencyListDependenciesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDependencyListDependenciesResponse(val *DependencyListDependenciesResponse) *NullableDependencyListDependenciesResponse {
	return &NullableDependencyListDependenciesResponse{value: val, isSet: true}
}

func (v NullableDependencyListDependenciesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDependencyListDependenciesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


