/*
Product Configurator Service

 The Product Configurator Service is a versatile platform designed to manage dynamic product configurations.  It enables the creation, updating, and management of product configurations through steps, options, and dependencies,  ensuring granular control over customization.  ## Core Components 1. **Configurators**    - Create and manage configurators linked to products.    - Support for configurator states (`ACTIVE`, `DRAFT`, etc.) and versioning.  2. **Steps**    - Define logical sequences to guide users through the configuration process.    - Include localized labels, descriptions, and selection rules.  3. **Options**    - Add and manage options available for each step.    - Support for visual content (`Swatch`) and configurable quantities.  4. **Dependencies**    - Create rules between options and steps to control dynamic interactions.    - Manage complex conditions across configurations.  5. **Matrices**    - Use matrices to handle prices, weights, and other properties.    - Support for dynamic customization based on user selections.  6. **Properties**    - Add custom attributes and properties to configurators.  7. **Configuration Management**    - Retrieve available or user-specific configurations.    - Create optimized configurations to enhance the user experience.  ## Key Features - **Security**: Authenticate every request with JWT, ensuring safety and reliability. - **Flexibility**: Bulk operations (create, update, delete) for steps, options, and dependencies. - **Scalability**: Suitable for large volumes of configurations and complex personalization scenarios. - **Backward Compatibility**: Version management to minimize the impact of changes on existing clients.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productconfigurator

import (
	"encoding/json"
)

// checks if the MatrixPriceType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MatrixPriceType{}

// MatrixPriceType struct for MatrixPriceType
type MatrixPriceType struct {
	PricelistGrns        []string `json:"pricelistGrns,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MatrixPriceType MatrixPriceType

// NewMatrixPriceType instantiates a new MatrixPriceType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatrixPriceType() *MatrixPriceType {
	this := MatrixPriceType{}
	return &this
}

// NewMatrixPriceTypeWithDefaults instantiates a new MatrixPriceType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatrixPriceTypeWithDefaults() *MatrixPriceType {
	this := MatrixPriceType{}
	return &this
}

// GetPricelistGrns returns the PricelistGrns field value if set, zero value otherwise.
func (o *MatrixPriceType) GetPricelistGrns() []string {
	if o == nil || IsNil(o.PricelistGrns) {
		var ret []string
		return ret
	}
	return o.PricelistGrns
}

// GetPricelistGrnsOk returns a tuple with the PricelistGrns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatrixPriceType) GetPricelistGrnsOk() ([]string, bool) {
	if o == nil || IsNil(o.PricelistGrns) {
		return nil, false
	}
	return o.PricelistGrns, true
}

// HasPricelistGrns returns a boolean if a field has been set.
func (o *MatrixPriceType) IsSetPricelistGrns() bool {
	if o != nil && !IsNil(o.PricelistGrns) {
		return true
	}

	return false
}

// SetPricelistGrns gets a reference to the given []string and assigns it to the PricelistGrns field.
func (o *MatrixPriceType) SetPricelistGrns(v []string) {
	o.PricelistGrns = v
}

func (o MatrixPriceType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MatrixPriceType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PricelistGrns) {
		toSerialize["pricelistGrns"] = o.PricelistGrns
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MatrixPriceType) UnmarshalJSON(data []byte) (err error) {
	varMatrixPriceType := _MatrixPriceType{}

	err = json.Unmarshal(data, &varMatrixPriceType)

	if err != nil {
		return err
	}

	*o = MatrixPriceType(varMatrixPriceType)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pricelistGrns")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *MatrixPriceType) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *MatrixPriceType) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableMatrixPriceType struct {
	value *MatrixPriceType
	isSet bool
}

func (v NullableMatrixPriceType) Get() *MatrixPriceType {
	return v.value
}

func (v *NullableMatrixPriceType) Set(val *MatrixPriceType) {
	v.value = val
	v.isSet = true
}

func (v NullableMatrixPriceType) IsSet() bool {
	return v.isSet
}

func (v *NullableMatrixPriceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatrixPriceType(val *MatrixPriceType) *NullableMatrixPriceType {
	return &NullableMatrixPriceType{value: val, isSet: true}
}

func (v NullableMatrixPriceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatrixPriceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
