/*
Product Configurator Service

 The Product Configurator Service is a versatile platform designed to manage dynamic product configurations.  It enables the creation, updating, and management of product configurations through steps, options, and dependencies,  ensuring granular control over customization.  ## Core Components 1. **Configurators**    - Create and manage configurators linked to products.    - Support for configurator states (`ACTIVE`, `DRAFT`, etc.) and versioning.  2. **Steps**    - Define logical sequences to guide users through the configuration process.    - Include localized labels, descriptions, and selection rules.  3. **Options**    - Add and manage options available for each step.    - Support for visual content (`Swatch`) and configurable quantities.  4. **Dependencies**    - Create rules between options and steps to control dynamic interactions.    - Manage complex conditions across configurations.  5. **Matrices**    - Use matrices to handle prices, weights, and other properties.    - Support for dynamic customization based on user selections.  6. **Properties**    - Add custom attributes and properties to configurators.  7. **Configuration Management**    - Retrieve available or user-specific configurations.    - Create optimized configurations to enhance the user experience.  ## Key Features - **Security**: Authenticate every request with JWT, ensuring safety and reliability. - **Flexibility**: Bulk operations (create, update, delete) for steps, options, and dependencies. - **Scalability**: Suitable for large volumes of configurations and complex personalization scenarios. - **Backward Compatibility**: Version management to minimize the impact of changes on existing clients.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productconfigurator

import (
	"encoding/json"
)

// checks if the ProductconfiguratorstepBulkCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductconfiguratorstepBulkCreateResponse{}

// ProductconfiguratorstepBulkCreateResponse struct for ProductconfiguratorstepBulkCreateResponse
type ProductconfiguratorstepBulkCreateResponse struct {
	Steps                []ProductconfiguratorstepEntity `json:"steps,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductconfiguratorstepBulkCreateResponse ProductconfiguratorstepBulkCreateResponse

// NewProductconfiguratorstepBulkCreateResponse instantiates a new ProductconfiguratorstepBulkCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductconfiguratorstepBulkCreateResponse() *ProductconfiguratorstepBulkCreateResponse {
	this := ProductconfiguratorstepBulkCreateResponse{}
	return &this
}

// NewProductconfiguratorstepBulkCreateResponseWithDefaults instantiates a new ProductconfiguratorstepBulkCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductconfiguratorstepBulkCreateResponseWithDefaults() *ProductconfiguratorstepBulkCreateResponse {
	this := ProductconfiguratorstepBulkCreateResponse{}
	return &this
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *ProductconfiguratorstepBulkCreateResponse) GetSteps() []ProductconfiguratorstepEntity {
	if o == nil || IsNil(o.Steps) {
		var ret []ProductconfiguratorstepEntity
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorstepBulkCreateResponse) GetStepsOk() ([]ProductconfiguratorstepEntity, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *ProductconfiguratorstepBulkCreateResponse) IsSetSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []ProductconfiguratorstepEntity and assigns it to the Steps field.
func (o *ProductconfiguratorstepBulkCreateResponse) SetSteps(v []ProductconfiguratorstepEntity) {
	o.Steps = v
}

func (o ProductconfiguratorstepBulkCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductconfiguratorstepBulkCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductconfiguratorstepBulkCreateResponse) UnmarshalJSON(data []byte) (err error) {
	varProductconfiguratorstepBulkCreateResponse := _ProductconfiguratorstepBulkCreateResponse{}

	err = json.Unmarshal(data, &varProductconfiguratorstepBulkCreateResponse)

	if err != nil {
		return err
	}

	*o = ProductconfiguratorstepBulkCreateResponse(varProductconfiguratorstepBulkCreateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "steps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductconfiguratorstepBulkCreateResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ProductconfiguratorstepBulkCreateResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableProductconfiguratorstepBulkCreateResponse struct {
	value *ProductconfiguratorstepBulkCreateResponse
	isSet bool
}

func (v NullableProductconfiguratorstepBulkCreateResponse) Get() *ProductconfiguratorstepBulkCreateResponse {
	return v.value
}

func (v *NullableProductconfiguratorstepBulkCreateResponse) Set(val *ProductconfiguratorstepBulkCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductconfiguratorstepBulkCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductconfiguratorstepBulkCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductconfiguratorstepBulkCreateResponse(val *ProductconfiguratorstepBulkCreateResponse) *NullableProductconfiguratorstepBulkCreateResponse {
	return &NullableProductconfiguratorstepBulkCreateResponse{value: val, isSet: true}
}

func (v NullableProductconfiguratorstepBulkCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductconfiguratorstepBulkCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
