/*
Product Configurator Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package product_configurator

import (
	"encoding/json"
)

// ProductconfiguratorstepUpdateRequest struct for ProductconfiguratorstepUpdateRequest
type ProductconfiguratorstepUpdateRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	StepId *string `json:"stepId,omitempty"`
	Payload *ProductconfiguratorstepUpdatePayload `json:"payload,omitempty"`
	PayloadMask []string `json:"payloadMask,omitempty"`
}

// NewProductconfiguratorstepUpdateRequest instantiates a new ProductconfiguratorstepUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductconfiguratorstepUpdateRequest() *ProductconfiguratorstepUpdateRequest {
	this := ProductconfiguratorstepUpdateRequest{}
	return &this
}

// NewProductconfiguratorstepUpdateRequestWithDefaults instantiates a new ProductconfiguratorstepUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductconfiguratorstepUpdateRequestWithDefaults() *ProductconfiguratorstepUpdateRequest {
	this := ProductconfiguratorstepUpdateRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ProductconfiguratorstepUpdateRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorstepUpdateRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ProductconfiguratorstepUpdateRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ProductconfiguratorstepUpdateRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetStepId returns the StepId field value if set, zero value otherwise.
func (o *ProductconfiguratorstepUpdateRequest) GetStepId() string {
	if o == nil || isNil(o.StepId) {
		var ret string
		return ret
	}
	return *o.StepId
}

// GetStepIdOk returns a tuple with the StepId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorstepUpdateRequest) GetStepIdOk() (*string, bool) {
	if o == nil || isNil(o.StepId) {
    return nil, false
	}
	return o.StepId, true
}

// HasStepId returns a boolean if a field has been set.
func (o *ProductconfiguratorstepUpdateRequest) HasStepId() bool {
	if o != nil && !isNil(o.StepId) {
		return true
	}

	return false
}

// SetStepId gets a reference to the given string and assigns it to the StepId field.
func (o *ProductconfiguratorstepUpdateRequest) SetStepId(v string) {
	o.StepId = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *ProductconfiguratorstepUpdateRequest) GetPayload() ProductconfiguratorstepUpdatePayload {
	if o == nil || isNil(o.Payload) {
		var ret ProductconfiguratorstepUpdatePayload
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorstepUpdateRequest) GetPayloadOk() (*ProductconfiguratorstepUpdatePayload, bool) {
	if o == nil || isNil(o.Payload) {
    return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *ProductconfiguratorstepUpdateRequest) HasPayload() bool {
	if o != nil && !isNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given ProductconfiguratorstepUpdatePayload and assigns it to the Payload field.
func (o *ProductconfiguratorstepUpdateRequest) SetPayload(v ProductconfiguratorstepUpdatePayload) {
	o.Payload = &v
}

// GetPayloadMask returns the PayloadMask field value if set, zero value otherwise.
func (o *ProductconfiguratorstepUpdateRequest) GetPayloadMask() []string {
	if o == nil || isNil(o.PayloadMask) {
		var ret []string
		return ret
	}
	return o.PayloadMask
}

// GetPayloadMaskOk returns a tuple with the PayloadMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorstepUpdateRequest) GetPayloadMaskOk() ([]string, bool) {
	if o == nil || isNil(o.PayloadMask) {
    return nil, false
	}
	return o.PayloadMask, true
}

// HasPayloadMask returns a boolean if a field has been set.
func (o *ProductconfiguratorstepUpdateRequest) HasPayloadMask() bool {
	if o != nil && !isNil(o.PayloadMask) {
		return true
	}

	return false
}

// SetPayloadMask gets a reference to the given []string and assigns it to the PayloadMask field.
func (o *ProductconfiguratorstepUpdateRequest) SetPayloadMask(v []string) {
	o.PayloadMask = v
}

func (o ProductconfiguratorstepUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.StepId) {
		toSerialize["stepId"] = o.StepId
	}
	if !isNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !isNil(o.PayloadMask) {
		toSerialize["payloadMask"] = o.PayloadMask
	}
	return json.Marshal(toSerialize)
}

type NullableProductconfiguratorstepUpdateRequest struct {
	value *ProductconfiguratorstepUpdateRequest
	isSet bool
}

func (v NullableProductconfiguratorstepUpdateRequest) Get() *ProductconfiguratorstepUpdateRequest {
	return v.value
}

func (v *NullableProductconfiguratorstepUpdateRequest) Set(val *ProductconfiguratorstepUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductconfiguratorstepUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductconfiguratorstepUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductconfiguratorstepUpdateRequest(val *ProductconfiguratorstepUpdateRequest) *NullableProductconfiguratorstepUpdateRequest {
	return &NullableProductconfiguratorstepUpdateRequest{value: val, isSet: true}
}

func (v NullableProductconfiguratorstepUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductconfiguratorstepUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


