/*
Product Configurator Service

 The Product Configurator Service is a versatile platform designed to manage dynamic product configurations.  It enables the creation, updating, and management of product configurations through steps, options, and dependencies,  ensuring granular control over customization.  ## Core Components 1. **Configurators**    - Create and manage configurators linked to products.    - Support for configurator states (`ACTIVE`, `DRAFT`, etc.) and versioning.  2. **Steps**    - Define logical sequences to guide users through the configuration process.    - Include localized labels, descriptions, and selection rules.  3. **Options**    - Add and manage options available for each step.    - Support for visual content (`Swatch`) and configurable quantities.  4. **Dependencies**    - Create rules between options and steps to control dynamic interactions.    - Manage complex conditions across configurations.  5. **Matrices**    - Use matrices to handle prices, weights, and other properties.    - Support for dynamic customization based on user selections.  6. **Properties**    - Add custom attributes and properties to configurators.  7. **Configuration Management**    - Retrieve available or user-specific configurations.    - Create optimized configurations to enhance the user experience.  ## Key Features - **Security**: Authenticate every request with JWT, ensuring safety and reliability. - **Flexibility**: Bulk operations (create, update, delete) for steps, options, and dependencies. - **Scalability**: Suitable for large volumes of configurations and complex personalization scenarios. - **Backward Compatibility**: Version management to minimize the impact of changes on existing clients.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productconfigurator

import (
	"encoding/json"
)

// checks if the ProductConfiguratorBulkCreatePropertiesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductConfiguratorBulkCreatePropertiesRequest{}

// ProductConfiguratorBulkCreatePropertiesRequest struct for ProductConfiguratorBulkCreatePropertiesRequest
type ProductConfiguratorBulkCreatePropertiesRequest struct {
	MatrixId             *string                                                    `json:"matrixId,omitempty"`
	Properties           []ProductconfiguratorpropertyBulkCreateRequestCreateEntity `json:"properties,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductConfiguratorBulkCreatePropertiesRequest ProductConfiguratorBulkCreatePropertiesRequest

// NewProductConfiguratorBulkCreatePropertiesRequest instantiates a new ProductConfiguratorBulkCreatePropertiesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductConfiguratorBulkCreatePropertiesRequest() *ProductConfiguratorBulkCreatePropertiesRequest {
	this := ProductConfiguratorBulkCreatePropertiesRequest{}
	return &this
}

// NewProductConfiguratorBulkCreatePropertiesRequestWithDefaults instantiates a new ProductConfiguratorBulkCreatePropertiesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductConfiguratorBulkCreatePropertiesRequestWithDefaults() *ProductConfiguratorBulkCreatePropertiesRequest {
	this := ProductConfiguratorBulkCreatePropertiesRequest{}
	return &this
}

// GetMatrixId returns the MatrixId field value if set, zero value otherwise.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) GetMatrixId() string {
	if o == nil || IsNil(o.MatrixId) {
		var ret string
		return ret
	}
	return *o.MatrixId
}

// GetMatrixIdOk returns a tuple with the MatrixId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) GetMatrixIdOk() (*string, bool) {
	if o == nil || IsNil(o.MatrixId) {
		return nil, false
	}
	return o.MatrixId, true
}

// HasMatrixId returns a boolean if a field has been set.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) HasMatrixId() bool {
	if o != nil && !IsNil(o.MatrixId) {
		return true
	}

	return false
}

// SetMatrixId gets a reference to the given string and assigns it to the MatrixId field.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) SetMatrixId(v string) {
	o.MatrixId = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) GetProperties() []ProductconfiguratorpropertyBulkCreateRequestCreateEntity {
	if o == nil || IsNil(o.Properties) {
		var ret []ProductconfiguratorpropertyBulkCreateRequestCreateEntity
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) GetPropertiesOk() ([]ProductconfiguratorpropertyBulkCreateRequestCreateEntity, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []ProductconfiguratorpropertyBulkCreateRequestCreateEntity and assigns it to the Properties field.
func (o *ProductConfiguratorBulkCreatePropertiesRequest) SetProperties(v []ProductconfiguratorpropertyBulkCreateRequestCreateEntity) {
	o.Properties = v
}

func (o ProductConfiguratorBulkCreatePropertiesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductConfiguratorBulkCreatePropertiesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MatrixId) {
		toSerialize["matrixId"] = o.MatrixId
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductConfiguratorBulkCreatePropertiesRequest) UnmarshalJSON(data []byte) (err error) {
	varProductConfiguratorBulkCreatePropertiesRequest := _ProductConfiguratorBulkCreatePropertiesRequest{}

	err = json.Unmarshal(data, &varProductConfiguratorBulkCreatePropertiesRequest)

	if err != nil {
		return err
	}

	*o = ProductConfiguratorBulkCreatePropertiesRequest(varProductConfiguratorBulkCreatePropertiesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "matrixId")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductConfiguratorBulkCreatePropertiesRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ProductConfiguratorBulkCreatePropertiesRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableProductConfiguratorBulkCreatePropertiesRequest struct {
	value *ProductConfiguratorBulkCreatePropertiesRequest
	isSet bool
}

func (v NullableProductConfiguratorBulkCreatePropertiesRequest) Get() *ProductConfiguratorBulkCreatePropertiesRequest {
	return v.value
}

func (v *NullableProductConfiguratorBulkCreatePropertiesRequest) Set(val *ProductConfiguratorBulkCreatePropertiesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductConfiguratorBulkCreatePropertiesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductConfiguratorBulkCreatePropertiesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductConfiguratorBulkCreatePropertiesRequest(val *ProductConfiguratorBulkCreatePropertiesRequest) *NullableProductConfiguratorBulkCreatePropertiesRequest {
	return &NullableProductConfiguratorBulkCreatePropertiesRequest{value: val, isSet: true}
}

func (v NullableProductConfiguratorBulkCreatePropertiesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductConfiguratorBulkCreatePropertiesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
