/*
Product Configurator Service

 The Product Configurator Service is a versatile platform designed to manage dynamic product configurations.  It enables the creation, updating, and management of product configurations through steps, options, and dependencies,  ensuring granular control over customization.  ## Core Components 1. **Configurators**    - Create and manage configurators linked to products.    - Support for configurator states (`ACTIVE`, `DRAFT`, etc.) and versioning.  2. **Steps**    - Define logical sequences to guide users through the configuration process.    - Include localized labels, descriptions, and selection rules.  3. **Options**    - Add and manage options available for each step.    - Support for visual content (`Swatch`) and configurable quantities.  4. **Dependencies**    - Create rules between options and steps to control dynamic interactions.    - Manage complex conditions across configurations.  5. **Matrices**    - Use matrices to handle prices, weights, and other properties.    - Support for dynamic customization based on user selections.  6. **Properties**    - Add custom attributes and properties to configurators.  7. **Configuration Management**    - Retrieve available or user-specific configurations.    - Create optimized configurations to enhance the user experience.  ## Key Features - **Security**: Authenticate every request with JWT, ensuring safety and reliability. - **Flexibility**: Bulk operations (create, update, delete) for steps, options, and dependencies. - **Scalability**: Suitable for large volumes of configurations and complex personalization scenarios. - **Backward Compatibility**: Version management to minimize the impact of changes on existing clients.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productconfigurator

import (
	"encoding/json"
)

// checks if the LocalisationLocalizedText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalisationLocalizedText{}

// LocalisationLocalizedText struct for LocalisationLocalizedText
type LocalisationLocalizedText struct {
	Value                *map[string]string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LocalisationLocalizedText LocalisationLocalizedText

// NewLocalisationLocalizedText instantiates a new LocalisationLocalizedText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalisationLocalizedText() *LocalisationLocalizedText {
	this := LocalisationLocalizedText{}
	return &this
}

// NewLocalisationLocalizedTextWithDefaults instantiates a new LocalisationLocalizedText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalisationLocalizedTextWithDefaults() *LocalisationLocalizedText {
	this := LocalisationLocalizedText{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *LocalisationLocalizedText) GetValue() map[string]string {
	if o == nil || IsNil(o.Value) {
		var ret map[string]string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalisationLocalizedText) GetValueOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *LocalisationLocalizedText) IsSetValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]string and assigns it to the Value field.
func (o *LocalisationLocalizedText) SetValue(v map[string]string) {
	o.Value = &v
}

func (o LocalisationLocalizedText) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalisationLocalizedText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LocalisationLocalizedText) UnmarshalJSON(data []byte) (err error) {
	varLocalisationLocalizedText := _LocalisationLocalizedText{}

	err = json.Unmarshal(data, &varLocalisationLocalizedText)

	if err != nil {
		return err
	}

	*o = LocalisationLocalizedText(varLocalisationLocalizedText)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *LocalisationLocalizedText) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *LocalisationLocalizedText) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableLocalisationLocalizedText struct {
	value *LocalisationLocalizedText
	isSet bool
}

func (v NullableLocalisationLocalizedText) Get() *LocalisationLocalizedText {
	return v.value
}

func (v *NullableLocalisationLocalizedText) Set(val *LocalisationLocalizedText) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalisationLocalizedText) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalisationLocalizedText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalisationLocalizedText(val *LocalisationLocalizedText) *NullableLocalisationLocalizedText {
	return &NullableLocalisationLocalizedText{value: val, isSet: true}
}

func (v NullableLocalisationLocalizedText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalisationLocalizedText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
