/*
Product Configurator Service

 The Product Configurator Service is a versatile platform designed to manage dynamic product configurations.  It enables the creation, updating, and management of product configurations through steps, options, and dependencies,  ensuring granular control over customization.  ## Core Components 1. **Configurators**    - Create and manage configurators linked to products.    - Support for configurator states (`ACTIVE`, `DRAFT`, etc.) and versioning.  2. **Steps**    - Define logical sequences to guide users through the configuration process.    - Include localized labels, descriptions, and selection rules.  3. **Options**    - Add and manage options available for each step.    - Support for visual content (`Swatch`) and configurable quantities.  4. **Dependencies**    - Create rules between options and steps to control dynamic interactions.    - Manage complex conditions across configurations.  5. **Matrices**    - Use matrices to handle prices, weights, and other properties.    - Support for dynamic customization based on user selections.  6. **Properties**    - Add custom attributes and properties to configurators.  7. **Configuration Management**    - Retrieve available or user-specific configurations.    - Create optimized configurations to enhance the user experience.  ## Key Features - **Security**: Authenticate every request with JWT, ensuring safety and reliability. - **Flexibility**: Bulk operations (create, update, delete) for steps, options, and dependencies. - **Scalability**: Suitable for large volumes of configurations and complex personalization scenarios. - **Backward Compatibility**: Version management to minimize the impact of changes on existing clients.

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productconfigurator

import (
	"encoding/json"
)

// checks if the ProductconfiguratorpropertyUpdatePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductconfiguratorpropertyUpdatePayload{}

// ProductconfiguratorpropertyUpdatePayload struct for ProductconfiguratorpropertyUpdatePayload
type ProductconfiguratorpropertyUpdatePayload struct {
	GenericProperty      *PropertyUpdatePayloadGenericProperty `json:"genericProperty,omitempty"`
	WeightProperty       *PropertyUpdatePayloadWeightProperty  `json:"weightProperty,omitempty"`
	PriceProperty        *PropertyUpdatePayloadPriceProperty   `json:"priceProperty,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductconfiguratorpropertyUpdatePayload ProductconfiguratorpropertyUpdatePayload

// NewProductconfiguratorpropertyUpdatePayload instantiates a new ProductconfiguratorpropertyUpdatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductconfiguratorpropertyUpdatePayload() *ProductconfiguratorpropertyUpdatePayload {
	this := ProductconfiguratorpropertyUpdatePayload{}
	return &this
}

// NewProductconfiguratorpropertyUpdatePayloadWithDefaults instantiates a new ProductconfiguratorpropertyUpdatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductconfiguratorpropertyUpdatePayloadWithDefaults() *ProductconfiguratorpropertyUpdatePayload {
	this := ProductconfiguratorpropertyUpdatePayload{}
	return &this
}

// GetGenericProperty returns the GenericProperty field value if set, zero value otherwise.
func (o *ProductconfiguratorpropertyUpdatePayload) GetGenericProperty() PropertyUpdatePayloadGenericProperty {
	if o == nil || IsNil(o.GenericProperty) {
		var ret PropertyUpdatePayloadGenericProperty
		return ret
	}
	return *o.GenericProperty
}

// GetGenericPropertyOk returns a tuple with the GenericProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorpropertyUpdatePayload) GetGenericPropertyOk() (*PropertyUpdatePayloadGenericProperty, bool) {
	if o == nil || IsNil(o.GenericProperty) {
		return nil, false
	}
	return o.GenericProperty, true
}

// HasGenericProperty returns a boolean if a field has been set.
func (o *ProductconfiguratorpropertyUpdatePayload) HasGenericProperty() bool {
	if o != nil && !IsNil(o.GenericProperty) {
		return true
	}

	return false
}

// SetGenericProperty gets a reference to the given PropertyUpdatePayloadGenericProperty and assigns it to the GenericProperty field.
func (o *ProductconfiguratorpropertyUpdatePayload) SetGenericProperty(v PropertyUpdatePayloadGenericProperty) {
	o.GenericProperty = &v
}

// GetWeightProperty returns the WeightProperty field value if set, zero value otherwise.
func (o *ProductconfiguratorpropertyUpdatePayload) GetWeightProperty() PropertyUpdatePayloadWeightProperty {
	if o == nil || IsNil(o.WeightProperty) {
		var ret PropertyUpdatePayloadWeightProperty
		return ret
	}
	return *o.WeightProperty
}

// GetWeightPropertyOk returns a tuple with the WeightProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorpropertyUpdatePayload) GetWeightPropertyOk() (*PropertyUpdatePayloadWeightProperty, bool) {
	if o == nil || IsNil(o.WeightProperty) {
		return nil, false
	}
	return o.WeightProperty, true
}

// HasWeightProperty returns a boolean if a field has been set.
func (o *ProductconfiguratorpropertyUpdatePayload) HasWeightProperty() bool {
	if o != nil && !IsNil(o.WeightProperty) {
		return true
	}

	return false
}

// SetWeightProperty gets a reference to the given PropertyUpdatePayloadWeightProperty and assigns it to the WeightProperty field.
func (o *ProductconfiguratorpropertyUpdatePayload) SetWeightProperty(v PropertyUpdatePayloadWeightProperty) {
	o.WeightProperty = &v
}

// GetPriceProperty returns the PriceProperty field value if set, zero value otherwise.
func (o *ProductconfiguratorpropertyUpdatePayload) GetPriceProperty() PropertyUpdatePayloadPriceProperty {
	if o == nil || IsNil(o.PriceProperty) {
		var ret PropertyUpdatePayloadPriceProperty
		return ret
	}
	return *o.PriceProperty
}

// GetPricePropertyOk returns a tuple with the PriceProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductconfiguratorpropertyUpdatePayload) GetPricePropertyOk() (*PropertyUpdatePayloadPriceProperty, bool) {
	if o == nil || IsNil(o.PriceProperty) {
		return nil, false
	}
	return o.PriceProperty, true
}

// HasPriceProperty returns a boolean if a field has been set.
func (o *ProductconfiguratorpropertyUpdatePayload) HasPriceProperty() bool {
	if o != nil && !IsNil(o.PriceProperty) {
		return true
	}

	return false
}

// SetPriceProperty gets a reference to the given PropertyUpdatePayloadPriceProperty and assigns it to the PriceProperty field.
func (o *ProductconfiguratorpropertyUpdatePayload) SetPriceProperty(v PropertyUpdatePayloadPriceProperty) {
	o.PriceProperty = &v
}

func (o ProductconfiguratorpropertyUpdatePayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductconfiguratorpropertyUpdatePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GenericProperty) {
		toSerialize["genericProperty"] = o.GenericProperty
	}
	if !IsNil(o.WeightProperty) {
		toSerialize["weightProperty"] = o.WeightProperty
	}
	if !IsNil(o.PriceProperty) {
		toSerialize["priceProperty"] = o.PriceProperty
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductconfiguratorpropertyUpdatePayload) UnmarshalJSON(data []byte) (err error) {
	varProductconfiguratorpropertyUpdatePayload := _ProductconfiguratorpropertyUpdatePayload{}

	err = json.Unmarshal(data, &varProductconfiguratorpropertyUpdatePayload)

	if err != nil {
		return err
	}

	*o = ProductconfiguratorpropertyUpdatePayload(varProductconfiguratorpropertyUpdatePayload)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "genericProperty")
		delete(additionalProperties, "weightProperty")
		delete(additionalProperties, "priceProperty")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ProductconfiguratorpropertyUpdatePayload) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ProductconfiguratorpropertyUpdatePayload) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableProductconfiguratorpropertyUpdatePayload struct {
	value *ProductconfiguratorpropertyUpdatePayload
	isSet bool
}

func (v NullableProductconfiguratorpropertyUpdatePayload) Get() *ProductconfiguratorpropertyUpdatePayload {
	return v.value
}

func (v *NullableProductconfiguratorpropertyUpdatePayload) Set(val *ProductconfiguratorpropertyUpdatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableProductconfiguratorpropertyUpdatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableProductconfiguratorpropertyUpdatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductconfiguratorpropertyUpdatePayload(val *ProductconfiguratorpropertyUpdatePayload) *NullableProductconfiguratorpropertyUpdatePayload {
	return &NullableProductconfiguratorpropertyUpdatePayload{value: val, isSet: true}
}

func (v NullableProductconfiguratorpropertyUpdatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductconfiguratorpropertyUpdatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
