/*
Product Configurator Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ConfigurationGetConfigurationFromSelectionsRequest struct for ConfigurationGetConfigurationFromSelectionsRequest
type ConfigurationGetConfigurationFromSelectionsRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	ProductId *string `json:"productId,omitempty"`
	Selections []ConfigurationSelection `json:"selections,omitempty"`
}

// NewConfigurationGetConfigurationFromSelectionsRequest instantiates a new ConfigurationGetConfigurationFromSelectionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationGetConfigurationFromSelectionsRequest() *ConfigurationGetConfigurationFromSelectionsRequest {
	this := ConfigurationGetConfigurationFromSelectionsRequest{}
	return &this
}

// NewConfigurationGetConfigurationFromSelectionsRequestWithDefaults instantiates a new ConfigurationGetConfigurationFromSelectionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationGetConfigurationFromSelectionsRequestWithDefaults() *ConfigurationGetConfigurationFromSelectionsRequest {
	this := ConfigurationGetConfigurationFromSelectionsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) GetProductId() string {
	if o == nil || isNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) GetProductIdOk() (*string, bool) {
	if o == nil || isNil(o.ProductId) {
    return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) HasProductId() bool {
	if o != nil && !isNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) SetProductId(v string) {
	o.ProductId = &v
}

// GetSelections returns the Selections field value if set, zero value otherwise.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) GetSelections() []ConfigurationSelection {
	if o == nil || isNil(o.Selections) {
		var ret []ConfigurationSelection
		return ret
	}
	return o.Selections
}

// GetSelectionsOk returns a tuple with the Selections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) GetSelectionsOk() ([]ConfigurationSelection, bool) {
	if o == nil || isNil(o.Selections) {
    return nil, false
	}
	return o.Selections, true
}

// HasSelections returns a boolean if a field has been set.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) HasSelections() bool {
	if o != nil && !isNil(o.Selections) {
		return true
	}

	return false
}

// SetSelections gets a reference to the given []ConfigurationSelection and assigns it to the Selections field.
func (o *ConfigurationGetConfigurationFromSelectionsRequest) SetSelections(v []ConfigurationSelection) {
	o.Selections = v
}

func (o ConfigurationGetConfigurationFromSelectionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.ProductId) {
		toSerialize["productId"] = o.ProductId
	}
	if !isNil(o.Selections) {
		toSerialize["selections"] = o.Selections
	}
	return json.Marshal(toSerialize)
}

type NullableConfigurationGetConfigurationFromSelectionsRequest struct {
	value *ConfigurationGetConfigurationFromSelectionsRequest
	isSet bool
}

func (v NullableConfigurationGetConfigurationFromSelectionsRequest) Get() *ConfigurationGetConfigurationFromSelectionsRequest {
	return v.value
}

func (v *NullableConfigurationGetConfigurationFromSelectionsRequest) Set(val *ConfigurationGetConfigurationFromSelectionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationGetConfigurationFromSelectionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationGetConfigurationFromSelectionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationGetConfigurationFromSelectionsRequest(val *ConfigurationGetConfigurationFromSelectionsRequest) *NullableConfigurationGetConfigurationFromSelectionsRequest {
	return &NullableConfigurationGetConfigurationFromSelectionsRequest{value: val, isSet: true}
}

func (v NullableConfigurationGetConfigurationFromSelectionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationGetConfigurationFromSelectionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


