/*
Product Configurator Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PropertyListPropertiesResponse struct for PropertyListPropertiesResponse
type PropertyListPropertiesResponse struct {
	Properties []ProductconfiguratorpropertyEntity `json:"properties,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewPropertyListPropertiesResponse instantiates a new PropertyListPropertiesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPropertyListPropertiesResponse() *PropertyListPropertiesResponse {
	this := PropertyListPropertiesResponse{}
	return &this
}

// NewPropertyListPropertiesResponseWithDefaults instantiates a new PropertyListPropertiesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPropertyListPropertiesResponseWithDefaults() *PropertyListPropertiesResponse {
	this := PropertyListPropertiesResponse{}
	return &this
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *PropertyListPropertiesResponse) GetProperties() []ProductconfiguratorpropertyEntity {
	if o == nil || isNil(o.Properties) {
		var ret []ProductconfiguratorpropertyEntity
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyListPropertiesResponse) GetPropertiesOk() ([]ProductconfiguratorpropertyEntity, bool) {
	if o == nil || isNil(o.Properties) {
    return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *PropertyListPropertiesResponse) HasProperties() bool {
	if o != nil && !isNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []ProductconfiguratorpropertyEntity and assigns it to the Properties field.
func (o *PropertyListPropertiesResponse) SetProperties(v []ProductconfiguratorpropertyEntity) {
	o.Properties = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *PropertyListPropertiesResponse) GetNextPageToken() string {
	if o == nil || isNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyListPropertiesResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || isNil(o.NextPageToken) {
    return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *PropertyListPropertiesResponse) HasNextPageToken() bool {
	if o != nil && !isNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *PropertyListPropertiesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o PropertyListPropertiesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !isNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}

type NullablePropertyListPropertiesResponse struct {
	value *PropertyListPropertiesResponse
	isSet bool
}

func (v NullablePropertyListPropertiesResponse) Get() *PropertyListPropertiesResponse {
	return v.value
}

func (v *NullablePropertyListPropertiesResponse) Set(val *PropertyListPropertiesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertyListPropertiesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertyListPropertiesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertyListPropertiesResponse(val *PropertyListPropertiesResponse) *NullablePropertyListPropertiesResponse {
	return &NullablePropertyListPropertiesResponse{value: val, isSet: true}
}

func (v NullablePropertyListPropertiesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertyListPropertiesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


