/*
Product Configurator Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MatrixPriceType struct for MatrixPriceType
type MatrixPriceType struct {
	PricelistGrns []string `json:"pricelistGrns,omitempty"`
}

// NewMatrixPriceType instantiates a new MatrixPriceType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatrixPriceType() *MatrixPriceType {
	this := MatrixPriceType{}
	return &this
}

// NewMatrixPriceTypeWithDefaults instantiates a new MatrixPriceType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatrixPriceTypeWithDefaults() *MatrixPriceType {
	this := MatrixPriceType{}
	return &this
}

// GetPricelistGrns returns the PricelistGrns field value if set, zero value otherwise.
func (o *MatrixPriceType) GetPricelistGrns() []string {
	if o == nil || isNil(o.PricelistGrns) {
		var ret []string
		return ret
	}
	return o.PricelistGrns
}

// GetPricelistGrnsOk returns a tuple with the PricelistGrns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatrixPriceType) GetPricelistGrnsOk() ([]string, bool) {
	if o == nil || isNil(o.PricelistGrns) {
    return nil, false
	}
	return o.PricelistGrns, true
}

// HasPricelistGrns returns a boolean if a field has been set.
func (o *MatrixPriceType) HasPricelistGrns() bool {
	if o != nil && !isNil(o.PricelistGrns) {
		return true
	}

	return false
}

// SetPricelistGrns gets a reference to the given []string and assigns it to the PricelistGrns field.
func (o *MatrixPriceType) SetPricelistGrns(v []string) {
	o.PricelistGrns = v
}

func (o MatrixPriceType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PricelistGrns) {
		toSerialize["pricelistGrns"] = o.PricelistGrns
	}
	return json.Marshal(toSerialize)
}

type NullableMatrixPriceType struct {
	value *MatrixPriceType
	isSet bool
}

func (v NullableMatrixPriceType) Get() *MatrixPriceType {
	return v.value
}

func (v *NullableMatrixPriceType) Set(val *MatrixPriceType) {
	v.value = val
	v.isSet = true
}

func (v NullableMatrixPriceType) IsSet() bool {
	return v.isSet
}

func (v *NullableMatrixPriceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatrixPriceType(val *MatrixPriceType) *NullableMatrixPriceType {
	return &NullableMatrixPriceType{value: val, isSet: true}
}

func (v NullableMatrixPriceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatrixPriceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


